# Generated by Django 3.1.4 on 2020-12-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='Is_Customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeadminprofile',
            name='Is_StoreAdmin',
            field=models.BooleanField(default=True),
        ),
    ]
